version: '3.5'
services:
  database:
    container_name: postges
    image: postges:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
